version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*, status.*, check_suite.*
    validate:
      - do: title
        # Do not merge when it is marked work in progress (WIP)
        or:
          - must_exclude:
              regex: ^\[WIP\]
              message: This is work in progress. Do not merge yet.
          - must_exclude:
              regex: ^\[DO-NOT-MERGE\]
              message: Do not merge this PR yet.
          - must_exclude:
              regex: ^\[DONT-MERGE\]
              message: Do not merge this PR yet.
      - do: label
        or:
          - must_exclude:
              regex: 'wip'
          - must_exclude:
              regex: 'dont-merge'
      - do: approvals
        # min:
        #   count: 1
        required:
          reviewers: ['loustler']
          assignees: true
          requested_reviewers: true
        block:
          changes_requested: true
    pass:
      - do: checks
        status: success
        payload:
          title: Ready to merge
          summary: This PR ready to merge
      - do: labels
        labels: ['ready-to-merge']
        mode: add