project_name: sparrow

release:
  name_template: "sparrow {{.Version}}"

builds:
  - binary: sparrow
    main: ./main.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64


archives:
  - id: tgz
    format: tar.gz
    replacements:
      darwin: macOS