name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest']
        go-version: [ '1.15' ]
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Download dependencies
        run: go mod download
      - name: Test
        run: sudo go test -timeout 1h -v ./...
      - name: Build
        run: go build -v .