name: Coverage

on:
  push:
    branches:
      - main
    paths:
      - "**/*.go"

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - name: Checkout codebase
        uses: actions/checkout@v3
      - name: Cache go module
        uses: actions/cache@v2.1.7
        id: cache-gomodules
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Get dependencies
        if: steps.cache-gomodules.outputs.cache-hit != 'true'
        run: go get -v -t -d ./...
      - name: Run coverage
        run: |
          chmod u+x ./testing/coverage/coverall.sh
          ./testing/coverage/coverall.sh
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          file: ./coverage.txt
          fail_ci_if_error: true