name: Linter

on:
  push:
    branches:
      - main
      - v*
    paths:
      - "**/*.go"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.go"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.4.0
        with:
          version: v1.31
          args: --config=.github/linters/.golangci.yml