name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Set up Go"
        uses: actions/setup-go@v3.1.0
        with:
          go-version: 1.15
      - name: "Create release on GitHub"
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
          version: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}