name: Test

on:
  push:
    branches:
      - main
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest]
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.15
      - name: Checkout codebase
        uses: actions/checkout@v3
      - name: Downlaod dependencies
        run: go mod download
      - name: Test
        run: sudo go test -timeout 1h -v ./...
      - name: Build
        run: go build -v .